language: go
sudo: false
go:
  - 1.4.3
  - 1.5.3
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
script:
  - go test ./...
  - go build
  - ./hugo -s docs/
install:
  - go get github.com/stretchr/testify
  - go get -v ./...
