language: go
sudo: required
go:
  - 1.5.4
  - 1.6.2
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
script:
  - make check
  - go build -race
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  - gem install asciidoctor
  - sudo pip install docutils
install:
  - go get github.com/stretchr/testify
  - go get -v ./...
