language: go
sudo: false
dist: trusty
env:
  HUGO_BUILD_TAGS="extended"
git:
  depth: false
go:
  - 1.11
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - env GO111MODULE=on go get github.com/magefile/mage
 script:
  - mage -v test
  - mage -v check
  - mage -v hugo
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  - gem install asciidoctor
  - type asciidoctor
