language: go
sudo: required
go:
  - 1.6.4
  - 1.7.4
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make govendor
script:
  - make check
  # Test 64-bit alignment on 32-bit builds
  - env GOARCH=386 make test
  - go build -race
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor | gem install asciidoctor
  - sudo pip install docutils
