language: go
sudo: required
go:
  - 1.6.3
  - 1.7.1
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make govendor
script:
  - make check
  - go build -race
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  - sudo pip install docutils
