
  enableInlineShortcodes = false

  [exec]
    allow = ['^go$']
    osEnv = ['^PATH$']

  [funcs]
    getenv = ['^HUGO_', '^REPOSITORY_URL$']

  [http]
    methods = ['(?i)GET|POST']
    urls = ['.*']