baseURL = "http://example.com"

defaultContentLanguage = "en"

[taxonomies]

[languages]
[languages.en]
weight = 0
title  = "My multilingual site"
[[languages.en.menu.main]]
url = "/home"
name = "Home"
weight = 0
[[languages.en.menu.main]]
url = "/news"
name = "News"
weight = 1
[[languages.en.menu.main]]
url = "/about"
name = "About"
weight = 2

[languages.et]
weight = 1
title = "Minu mitmekeelne leht"
[[languages.et.menu.main]]
url = "/et/home"
name = "Kodu"
weight = 0
[[languages.et.menu.main]]
url = "/et/news"
name = "Uudised"
weight = 1
[[languages.et.menu.main]]
url = "/et/about"
name = "Minust"
weight = 2
