name: hugo
version: "0.50-DEV"
summary: Fast and Flexible Static Site Generator
description: |
  Hugo is a static HTML and CSS website generator written in Go. It is
  optimized for speed, easy use and configurability. Hugo takes a directory
  with content and templates and renders them into a full HTML website.
confinement: strict
grade: devel # "devel" or "stable"

apps:
  hugo:
    command: bin/hugo
    completer: hugo-completion
    plugs: [home, network-bind, removable-media]

parts:
  git:
    plugin: nil
    stage-packages:
      - git
    organize:
      usr/bin/: bin/
    prime:
      - bin/git

  go:
    # Hugo's go.mod would interfere with the build of Go 1.11 in the
    # parts/go/build/ subdirectory.  Move go.mod out of the way
    # as a workaround.  (Note: 'override-build' does not work here,
    # hence the use of the deprecated 'prepare' keyword.)
    # See https://forum.snapcraft.io/t/go-plugin-go1-11-fails-if-go-mod-exists-in-the-top-level-directory/7546
    prepare: |
      set -x
      ( cd ../../.. && mv -v go.mod go.mod~ )
    source-tag: go1.11

  hugo:
    source: .
    after: [go]
    plugin: go
    go-importpath: github.com/gohugoio/hugo
    override-build: |
      set -ex

      echo "\nStarting override-build:"
      ( cd ../../.. && mv -v go.mod~ go.mod || : )
      export GO111MODULE=on
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH

      cd $GOPATH/src/github.com/gohugoio/hugo
      echo ' * Running "go get -v github.com/magefile/mage"...'
      go get -v github.com/magefile/mage

      # Skipping "mage -v test" because "go test ./... -tags none" fails with
      # "use of internal package github.com/gohugoio/hugo/tpl/internal not allowed"
      # on autobuilder on Launchpad, see
      # https://launchpadlibrarian.net/390252700/buildlog_snap_ubuntu_xenial_amd64_hugo-dev_BUILDING.txt.gz
      #echo ' * Running "mage -v test"...'
      #mage -v test

      echo " * Building hugo (build tag: none)..."
      [ "$SNAPCRAFT_PROJECT_GRADE" = "stable" ] && mage -v hugoNoGitInfo || mage -v hugo
      ./hugo version
      ldd hugo || :

      echo " * Building shell completion..."
      ./hugo gen autocomplete --completionfile=hugo-completion

      echo " * Installing to ${SNAPCRAFT_PART_INSTALL}..."
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -av hugo $SNAPCRAFT_PART_INSTALL/bin/
      mv -v hugo-completion $SNAPCRAFT_PART_INSTALL/

      echo " * Stripping binary..."
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/hugo
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo

  node:
    plugin: nodejs
    node-packages: [postcss-cli]
    filesets:
      node:
        - bin/node
      postcss:
        - bin/postcss
        - lib/node_modules/postcss-cli/*
    prime:
      - $node
      - $postcss

  pygments:
    plugin: python
    python-packages: [Pygments]
    prime:
      - bin/pygmentize
      - lib/python*/site-packages/Pygments-*.dist-info/*
      - lib/python*/site-packages/pygments/*
      - usr/bin/python*
      - -usr/bin/python*m
      - usr/lib/python*/*
      - -usr/lib/python*/distutils/*
      - -usr/lib/python*/email/*
      - -usr/lib/python*/lib2to3/*
      - -usr/lib/python*/tkinter/*
      - -usr/lib/python*/unittest/*
